sudo: required

language: android

jdk:
  - oraclejdk8

branches:
  only:
  - master

before_install:
 - gradle -b src/android/wrapper.gradle wrapper
 - pwd
 - ls -la
 - chmod +x gradlew
 - sudo apt-get update -qq
 - sudo apt-get install ant
 
install:
 # Gradle
 #- gradle wrapper --gradle-version 5.1.1
 
 # Let's use the new command 'sdkmanager' to install Android SDK components
 - yes | sdkmanager --verbose "build-tools;26.0.3"
 - yes | sdkmanager --verbose "platform-tools"
 - yes | sdkmanager --verbose "tools"
 - yes | sdkmanager --verbose "platforms;android-26"
 - yes | sdkmanager --verbose "system-images;android-24;default;armeabi-v7a"

 # Check tools and dependencies installed
 - yes | sdkmanager --list

 # On the other hand, Travis still uses 'android' command behind the 'components' section update. 
 # That command is obsolete and cannot update Android SDK Tools after 25.2.5.
 # Let's solve it here with the new command 'sdkmanager'
 - yes | sdkmanager --verbose tools

script:
 - ./gradlew assemble
 - ./gradlew check
 - ./gradlew -p src/android clean build --scan -s
 #- gradle -p src/android clean build --scan -s

env:
  matrix:
  - ANDROID_TARGET=android-26 ANDROID_ABI=armeabi-v7a