version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - run:
          name: Download Dependencies
          working_directory: ~/code/src/android
          command: ./gradlew androidDependencies
      - run:
          name: Build
          working_directory: ~/code/src/android
          command: ./gradlew clean build --stacktrace